name: uxcaptain
services:
  # server:
  #   container_name: server
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   environment:
  #     NODE_ENV: ${NODE_ENV}
  #     DEPLOY_ENVIRONMENT: ${DEPLOY_ENVIRONMENT}
  #     POSTHOG_API_KEY: ${POSTHOG_API_KEY}
  #     SESSION_SECRET: ${SESSION_SECRET}
  #     BREVO_API_KEY: ${BREVO_API_KEY}
  #     PRISMA_POSTGRES_DIRECT_URL: ${PRISMA_POSTGRES_DIRECT_URL}
  #     PRISMA_POSTGRES_CONNECTION_STRING: ${PRISMA_POSTGRES_CONNECTION_STRING}
  #     TELEGRAM_BOT_API_KEY: ${TELEGRAM_BOT_API_KEY}
  #     FRONT_WEB_APP_ORIGIN_URL: ${FRONT_WEB_APP_ORIGIN_URL}
  #     STRIPE_API_KEY: ${STRIPE_API_KEY}
  #     STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
  #     PORT: ${PORT}
  #     AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  #     AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  #     AWS_BUCKET: dev-analysis-entry-storage
  #     S3_REGION: ${S3_REGION}

  #   ports:
  #     - 3000:3000
  #   develop:
  #     watch:
  #       - path: .
  #         action: sync+restart #* Synchronize code changes and restart the server
  #         target: /usr/src/app/
  #   depends_on: #* References the SERVICE name - NOT the container_name
  #     database:
  #       condition: service_started
  #     minio:
          # condition: service_started
  #   networks:
  #     - uxcaptain-network
  
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: on-failure
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - /Users/martaperezsanchez/repos/minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    networks:
      - uxcaptain-network
  
  database:
    image: postgres:17.5
    restart: on-failure
    container_name: postgresDB
    user: 
      postgres
    volumes:
      - uxcaptain-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - uxcaptain-network 

networks:
  uxcaptain-network:
    name: uxcaptain-network
    driver: bridge

volumes:
  uxcaptain-database:

