# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

name: uxcaptain-local
services:
  server:
    container_name: server
    image: sergion14/uxcaptain:server-local
    environment:
      NODE_ENV: development
      DEPLOY_ENVIRONMENT: production
      POSTHOG_API_KEY: phc_i35r1ELHgAh76WDXckKUf1A2A8DHHZNQNPv3AiaREmR
      SESSION_SECRET: 9c2ab4f1e3d8b7a5c6e9d2f4b7a8c5e3d6f9b2a5c8e3d6f9b2a5c8e3d6f9b2a5
      BREVO_API_KEY: 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
      BETTERSTACK_SOURCE_TOKEN: JhNP8CNrRGKTTxYPs2qqL5NM
      BETTERSTACK_INGESTING_HOST: https://s1499424.eu-nbg-2.betterstackdata.com
      PRISMA_POSTGRES_DIRECT_URL: postgresql://postgres:prismaORM124!@database:5433/public
      PRISMA_POSTGRES_CONNECTION_STRING: postgresql://postgres:prismaORM124!@database:5433/public
      TELEGRAM_BOT_API_KEY: 7983550336:AAFsGjXkqDNboE5-98REjaDDiuJx7u2eHVU
      FRONT_WEB_APP_ORIGIN_URL: https://next.uxcaptain.com
      STRIPE_API_KEY: rk_test_51S94zoKNsGqZfOkoxTPbXpF5LaDZ9HB0tho5yaEC6ugey49ME0gVoDHYbO41yUNqjIQaWoZoEiri8PZqunYfUGdp00YhGhjlI3
      STRIPE_WEBHOOK_SECRET: whsec_8a3b92ac9f885cb3c3b108df2ba567723ef39de30f0311edf1e5acfd45784f2d
      PORT: 3000
      AWS_ACCESS_KEY_ID: AKIAQTEOOHOGGDJ5YJFY
      AWS_SECRET_ACCESS_KEY: 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
    ports:
      - 3001:3000
    depends_on: #* References the SERVICE name - NOT the container_name
      database:
        condition: service_started
    networks:
      - uxcaptain-network
  
  webapp:
    container_name: webapp-next
    image: sergion14/uxcaptain:webapp-local
    restart: unless-stopped
    ports:
      - 8500:80
    networks:
      - nginxproxymanager

  database:
    image: postgres:17.5
    restart: on-failure
    container_name: core-database-local
    user: 
      postgres
    volumes:
      - uxcaptain-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=public
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=prismaORM124!
    ports:
      - 5433:5432
    networks:
      - uxcaptain-network 

networks:
  uxcaptain-network:
    name: uxcaptain-network
    driver: bridge

volumes:
  uxcaptain-database:
    name:
      uxcaptain-database-volume

